-- ============================================================================
-- EverGreen — Database schema (run this in Supabase → SQL Editor)
-- ----------------------------------------------------------------------------
-- Plain-English overview:
--   * "properties" holds every listing. Visitors can READ only the ones marked
--     published; only logged-in agency staff can add/edit/delete them.
--   * "leads" holds enquiries from the contact form and "request a viewing".
--     Nobody can read them except logged-in staff; they're written by the server.
--   * RLS (Row Level Security) is the lock on each table — it decides who may do
--     what. We never turn it off.
-- ============================================================================

-- ---- PROPERTIES ------------------------------------------------------------
create table if not exists public.properties (
  id          bigint generated by default as identity primary key,
  title       text    not null,
  location    text    not null,
  price       bigint  not null,
  type        text    not null,            -- House | Villa | Estate
  beds        int     not null default 0,
  baths       int     not null default 0,
  area        int     not null default 0,  -- square metres
  badge       text    not null default 'For Sale',
  img         text    not null,            -- main image URL
  description text    not null default '',
  gallery     jsonb   not null default '[]'::jsonb,   -- array of image URLs
  features    jsonb   not null default '[]'::jsonb,   -- array of strings
  year_built  int     not null default 0,
  garage      int     not null default 0,
  listing_type text   not null default 'sale',   -- 'sale' | 'rent'
  rent_period  text,                              -- 'month' for rentals
  lat         double precision not null default 0,
  lng         double precision not null default 0,
  published   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ---- LEADS -----------------------------------------------------------------
create table if not exists public.leads (
  id          bigint generated by default as identity primary key,
  name        text not null,
  email       text not null,
  phone       text,
  message     text not null default '',
  property_id bigint references public.properties(id) on delete set null,
  created_at  timestamptz not null default now()
);

-- ---- SUBSCRIBERS (newsletter) ----------------------------------------------
create table if not exists public.subscribers (
  id         bigint generated by default as identity primary key,
  email      text not null unique,
  created_at timestamptz not null default now()
);

-- ============================================================================
-- Row Level Security
-- ============================================================================
alter table public.properties  enable row level security;
alter table public.leads       enable row level security;
alter table public.subscribers enable row level security;

-- SUBSCRIBERS: only authenticated staff may read; inserts happen server-side
-- with the service-role key (no public policy = no public access).
drop policy if exists "authenticated can read subscribers" on public.subscribers;
create policy "authenticated can read subscribers"
  on public.subscribers for select to authenticated using (true);

-- PROPERTIES: anyone (even logged-out visitors) may read PUBLISHED listings.
drop policy if exists "public can read published properties" on public.properties;
create policy "public can read published properties"
  on public.properties for select
  using (published = true);

-- PROPERTIES: logged-in agency staff may read ALL listings (incl. unpublished).
drop policy if exists "authenticated can read all properties" on public.properties;
create policy "authenticated can read all properties"
  on public.properties for select to authenticated using (true);

-- PROPERTIES: only authenticated (logged-in agency) users may write.
drop policy if exists "authenticated can insert properties" on public.properties;
create policy "authenticated can insert properties"
  on public.properties for insert to authenticated with check (true);

drop policy if exists "authenticated can update properties" on public.properties;
create policy "authenticated can update properties"
  on public.properties for update to authenticated using (true) with check (true);

drop policy if exists "authenticated can delete properties" on public.properties;
create policy "authenticated can delete properties"
  on public.properties for delete to authenticated using (true);

-- LEADS: only authenticated staff may read them. (No public select policy = no
-- public reads.) Inserts happen server-side with the service-role key, which
-- bypasses RLS — so we deliberately do NOT add a public insert policy here.
drop policy if exists "authenticated can read leads" on public.leads;
create policy "authenticated can read leads"
  on public.leads for select to authenticated using (true);

-- ============================================================================
-- Storage bucket for listing photos (public read, authenticated write)
-- ============================================================================
insert into storage.buckets (id, name, public)
values ('property-images', 'property-images', true)
on conflict (id) do nothing;

drop policy if exists "public can view property images" on storage.objects;
create policy "public can view property images"
  on storage.objects for select
  using (bucket_id = 'property-images');

drop policy if exists "authenticated can upload property images" on storage.objects;
create policy "authenticated can upload property images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'property-images');

drop policy if exists "authenticated can delete property images" on storage.objects;
create policy "authenticated can delete property images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'property-images');
